<a href="https://colab.research.google.com/github/alshubati99/Data-Science-Study/blob/main/Data_Representation__NumPy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Data Representation NumPy
- standard python implementation is written in C, which means that every python object is simply a cleverly disguised C structure, which contains not only its value, but other information as well
- python list contains pointer to a block of pointers, each of which in turn points to a full python object like the python integer
- advantage of list is flexibility, because each list element is a full sturcture containing both data and type information, the list can be filled with data of any desired type.
### Similarities between lists and arrays:
    - both use sequare brackets `[]`
    - both data types are mutable, means you can replace, change items in list or array.
    - both can be indexed and used for slicing operations
    - list cannot directly handle a mathematical operations while array can
    - 2D arrays in python can be created using list of lists
    - all array element should be of same type, unlike lists
### Data Types
![data types.png]()

- *Attributes of array* : determine size, shape, memory consumption, and data types of arrays.
- *Indexing of array*: getting and setting value of individual elements.
- *reshaping of array*: changing the shape of given array.
- *joining and splitting  of arrays*: compining multiple arrays into one, and splitting one array into many.
- slicing returns view rather than copies of arrays, while in lists slices are copies of the list
- broadcasting numpy arrays = apply binary operations (*, +, -, /) on arrays of different sizes
- *Universal function in numpy* = simple mathmatical functions that operate in ND array
- *Fancy Indexing* = passing an array of indices to access multiple array elements at ones.


In [ ]:
list1 = [1,3,4]
list1

[1, 3, 4]

In [ ]:
import numpy as np
arr = np.array([1,3,4])
arr

array([1, 3, 4])

In [ ]:
list1[0] = 0
list1

[0, 3, 4]

In [ ]:
arr[0] = 0
arr

array([0, 3, 4])

In [ ]:
list1[2]

4

In [ ]:
arr[2]

4

In [ ]:
list1[:2]

[0, 3]

In [ ]:
arr[:2]

array([0, 3])

In [ ]:
arr[1:]

array([3, 4])

In [ ]:
list1*2

[0, 3, 4, 0, 3, 4]

In [ ]:
arr*2

array([0, 6, 8])

In [ ]:
np.array([2.1,4,5,5])

array([2.1, 4. , 5. , 5. ])

In [ ]:
# set data type of resulting array explicitly
np.array([1,3,4], dtype = 'float32')

array([1., 3., 4.], dtype=float32)

In [ ]:
# create matrix:
matrix = np.array([[1,4],[2,5]])
matrix

array([[1, 4],
       [2, 5]])

In [ ]:
# view shape
matrix.shape

(2, 2)

In [ ]:
twodim = np.array([[1,3],[5,5],[2,3]])
print(twodim)
print("number of Dimentions = ", twodim.ndim)
print('Dimention = ', twodim.shape)
print('size = ', twodim.size)
print('array type = ', twodim.dtype)

[[1 3]
 [5 5]
 [2 3]]
number of Dimentions =  2
Dimention =  (3, 2)
size =  6
array type =  int64


In [ ]:
# create length 10 integer array filled with zeros
np.zeros(10, dtype = int)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [ ]:
# create 3*5 matrix floating point array filled with ones
np.ones((3,5),dtype = float)

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [ ]:
# create an array filled with alinear sequence starting at 0 ending 20 stepping by 2(range func)
np.arange(0,20,2)


array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [ ]:
# create array of 5 values evenly spaced between 0 and 1
np.linspace(0,1,5)

array([0.  , 0.25, 0.5 , 0.75, 1.  ])

In [ ]:
# create 3x3 array of uniformly distributed random values between 0 and 1
np.random.random((3,3))

array([[0.81498153, 0.93340271, 0.25791565],
       [0.14867153, 0.58920514, 0.92417674],
       [0.75244367, 0.31879901, 0.35684621]])

In [ ]:
# create 3x3 array of normally distributed random values with mean = 0 and standard deviation 1
np.random.normal(0,10,(3,3))

array([[-4.20816886, -3.02885458,  1.1097691 ],
       [-1.81909699, 10.85930013, -3.73203204],
       [ 0.83974021, 14.99677172, 18.69389695]])

In [ ]:
# create 5x5 array of random integer in interval[0,10]
np.random.randint(0,10,(5,5))

array([[4, 7, 3, 6, 0],
       [9, 5, 0, 4, 2],
       [6, 4, 1, 9, 9],
       [7, 5, 2, 6, 9],
       [6, 7, 4, 5, 4]])

In [ ]:
# create 10x10 identity matrix
np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [3]:
import numpy as np
x1 = np.random.randint(10,size=6) #one-dimentional array
x2 = np.random.randint(10,size=(3,4)) # 2D array
x3 = np.random.randint(10, size=(3,4,5)) # 3D array
x1
x2
x3
print('x3 ndim', x3.ndim)
print('x3 shape', x3.shape)
print('x3 size', x3.size)

x3 ndim 3
x3 shape (3, 4, 5)
x3 size 60


In [4]:
# accessing numpy array elements
x1

array([8, 4, 0, 1, 9, 8])

In [5]:
x1[0]

8

In [6]:
x1[4]

9

In [7]:
x1[-1]

8

In [9]:
x1[-2]

9

In [10]:
# in multidimenstional array you can access itmes using a comma-separated tuple ofindices
x2

array([[9, 2, 6, 4],
       [7, 8, 2, 8],
       [1, 9, 1, 1]])

In [11]:
x2[0,0]

9

In [12]:
x2[2,0]

1

In [13]:
x2[2,-1]

1

In [15]:
# modify values using any of the above index notatoin
x2[0,0] = 88
x2

array([[88,  2,  6,  4],
       [ 7,  8,  2,  8],
       [ 1,  9,  1,  1]])

In [16]:
# slicing numpy array => array[start, stop, step]
x=np.arange(10)
x

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [17]:
x[:5] # first 5 elements

array([0, 1, 2, 3, 4])

In [18]:
x[:5] #last five elements

array([0, 1, 2, 3, 4])

In [19]:
x[4:7]

array([4, 5, 6])

In [20]:
x[::2] #every other element

array([0, 2, 4, 6, 8])

In [21]:
x[1::2] #every other element starting from 1

array([1, 3, 5, 7, 9])

In [22]:
# if step value is negative, defualt for start and stop are swapped=>reverse array

x[::-1] # all elements reveresed

array([9, 8, 7, 6, 5, 4, 3, 2, 1, 0])

In [23]:
x[5::-2] # reversed every other from index 5

array([5, 3, 1])

In [24]:
x2

array([[88,  2,  6,  4],
       [ 7,  8,  2,  8],
       [ 1,  9,  1,  1]])

In [25]:
x2[:2,:3]  #two rows and three columns

array([[88,  2,  6],
       [ 7,  8,  2]])

In [26]:
x2[:3,::2] # all rows, every other column

array([[88,  6],
       [ 7,  2],
       [ 1,  1]])

In [27]:
print(x2[:,0]) # first column

[88  7  1]


In [29]:
print(x2[0,:]) # first row

[88  2  6  4]


In [30]:
x2

array([[88,  2,  6,  4],
       [ 7,  8,  2,  8],
       [ 1,  9,  1,  1]])

In [32]:
x2_sub =x2[:2,:2]
print(x2_sub)

[[88  2]
 [ 7  8]]


In [33]:
x2_sub[1,1]=99
print(x2_sub)

[[88  2]
 [ 7 99]]


In [34]:
print(x2)

[[88  2  6  4]
 [ 7 99  2  8]
 [ 1  9  1  1]]


In [35]:
# to create a copy of numpy array

x2_sub_copy =x2[:2,:2].copy()
print(x2_sub_copy)

[[88  2]
 [ 7 99]]


In [37]:
x2_sub_copy[0,0]=42
x2_sub_copy

array([[42,  2],
       [ 7, 99]])

In [38]:
print(x2)

[[88  2  6  4]
 [ 7 99  2  8]
 [ 1  9  1  1]]


In [40]:
# reshaping arrays
grid =np.arange(1,10).reshape((3,3))
grid

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [42]:
# common reshaping pattern = conversion of none dimentional array into two-dimensional array
x = np.array([1,2,3])
x.reshape((1,3)) # row vector via reshape
x.reshape((3,1)) # column vector via reshape

array([[1],
       [2],
       [3]])

In [43]:
grid.flatten()

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [44]:
unsorted_array=  np.random.randint(1,50,20)
unsorted_array

array([19,  7, 47, 49, 27, 23, 15, 31,  5,  9, 31, 49, 41, 28, 13, 17, 47,
       24, 17, 15])

In [45]:
sorted_array  = np.sort(unsorted_array)
sorted_array

array([ 5,  7,  9, 13, 15, 15, 17, 17, 19, 23, 24, 27, 28, 31, 31, 41, 47,
       47, 49, 49])

In [46]:
unsorted_array=  np.random.randint(1,50, size = (3,4))
unsorted_array

array([[43, 20, 33,  5],
       [15,  3, 37, 18],
       [21, 27, 44, 26]])

In [47]:
np.sort(unsorted_array)

array([[ 5, 20, 33, 43],
       [ 3, 15, 18, 37],
       [21, 26, 27, 44]])

In [56]:
arr = np.array([2,3,50,1,3,8,7,66,77]).reshape(3,3)
print(arr)
sortIndex = np.argsort(arr,axis = 0)
print(sortIndex)


[[ 2  3 50]
 [ 1  3  8]
 [ 7 66 77]]
[[1 0 1]
 [0 1 0]
 [2 2 2]]


In [53]:
arr = np.array([2,3,50,1,3,8])
print(arr)

[ 2  3 50  1  3  8]


In [54]:
sortIndex = np.argsort(arr)
print(sortIndex)

[3 0 1 4 5 2]


In [57]:
arr = np.array([2,3,50,1,3,8,7,66,77]).reshape(3,3)
print(arr)
sortIndex = np.argsort(arr,axis = 1) #row
print(sortIndex)


[[ 2  3 50]
 [ 1  3  8]
 [ 7 66 77]]
[[0 1 2]
 [0 1 2]
 [0 1 2]]


In [63]:
a = np.array([[2,35,2],[4,5,2],[7,0,5]])
print(np.sort(a)) # sort row-wise


[[ 2  2 35]
 [ 2  4  5]
 [ 0  5  7]]


In [66]:
a = np.array([[2,35,2],[4,5,2],[7,0,5]])
b= np.sort(a, axis =0)
print(a)
print('---------------------')
print(b) # sort column wise


[[ 2 35  2]
 [ 4  5  2]
 [ 7  0  5]]
---------------------
[[ 2  0  2]
 [ 4  5  2]
 [ 7 35  5]]


In [68]:
np.concatenate([a,b]) # fist axis

array([[ 2, 35,  2],
       [ 4,  5,  2],
       [ 7,  0,  5],
       [ 2,  0,  2],
       [ 4,  5,  2],
       [ 7, 35,  5]])

In [69]:
np.concatenate([a,b], axis = 1) # second axis

array([[ 2, 35,  2,  2,  0,  2],
       [ 4,  5,  2,  4,  5,  2],
       [ 7,  0,  5,  7, 35,  5]])

In [4]:
import numpy as np
# np.vstack and np.hstack
a = np.array([[1,3,4],[2,3,5]])
b = np.array([1,3,4])
np.vstack([a,b])

array([[1, 3, 4],
       [2, 3, 5],
       [1, 3, 4]])

In [8]:
c = np.array([[22,44,55],[3,5,6]])
np.hstack([a,c])

array([[ 1,  3,  4, 22, 44, 55],
       [ 2,  3,  5,  3,  5,  6]])

In [11]:
x = [1,2,3,4,5,6,7]
x1,x2,x3 = np.split(x,[3,5])
print(x1,x2,x3)
x0 = [1,2,3,99,99,2,1]
x4, x5, x6 = np.split(x0,[3,5])
print(x4,x5,x6)

[1 2 3] [4 5] [6 7]
[1 2 3] [99 99] [2 1]


In [14]:
grid = np.arange(16).reshape((4,4))
grid

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [15]:
upper, lower = np.vsplit(grid,[2])
print(upper)
print(lower)

[[0 1 2 3]
 [4 5 6 7]]
[[ 8  9 10 11]
 [12 13 14 15]]


In [18]:
upper, lower = np.vsplit(grid,[3])
print(upper)
print(lower)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
[[12 13 14 15]]


In [19]:
# append, insert, delete on numpy arrays
y = np.array([0,1,2])
X = np.array([1,2,3,4,5,6]).reshape(2,3)
y= np.append(y,[3,4])
z = np.insert(y, 1,[5,6])
Y= np.delete(X,1,axis =0)
Z = np.delete(X,1,axis = 1)
print('for 1D array')
print(y)
print(z)
print('for 2D array')
print(X)
print(Y)
print(Z)


for 1D array
[0 1 2 3 4]
[0 5 6 1 2 3 4]
for 2D array
[[1 2 3]
 [4 5 6]]
[[1 2 3]]
[[1 3]
 [4 6]]


In [25]:
# numpy uses standard arithmatic operations +,-,*,/

x = np.arange(4)
print('x = ', x)
print('x+5 = ', x+5)
print('x-5 = ',x-5)
print('x*5 = ',x*5)
print('x/5 = ', x/5)
print('-x = ', -x)
print('x**2 = ', x**2)
print('x%2 = ', x%2)
print(np.add(x,2))
print(np.subtract(x,1))
print(np.negative(x))
print(np.multiply(x,4))
print(np.divide(x,2))
print(np.floor_divide(x,2))
print(np.power(x,5))
print(np.mod(x,5))

x =  [0 1 2 3]
x+5 =  [5 6 7 8]
x-5 =  [-5 -4 -3 -2]
x*5 =  [ 0  5 10 15]
x/5 =  [0.  0.2 0.4 0.6]
-x =  [ 0 -1 -2 -3]
x**2 =  [0 1 4 9]
x%2 =  [0 1 0 1]
[2 3 4 5]
[-1  0  1  2]
[ 0 -1 -2 -3]
[ 0  4  8 12]
[0.  0.5 1.  1.5]
[0 0 1 1]
[  0   1  32 243]
[0 1 2 3]


In [27]:
# absolute value
a = np.array([-5])
abs(a)

array([5])

In [28]:
np.absolute(a)

array([5])

In [29]:
np.abs(a)

array([5])

In [31]:
# trigonomteric functions
theta = np.linspace(0,np.pi,3)
print('theta = ', theta)
print('sin(theta) = ', np.sin(theta))
print('cos(theta) = ', np.cos(theta))
print('tan(theta) = ', np.tan(theta))

theta =  [0.         1.57079633 3.14159265]
sin(theta) =  [0.0000000e+00 1.0000000e+00 1.2246468e-16]
cos(theta) =  [ 1.000000e+00  6.123234e-17 -1.000000e+00]
tan(theta) =  [ 0.00000000e+00  1.63312394e+16 -1.22464680e-16]


In [32]:
# exponents and logarithms
x = [1,3,4]
print('x =',x)
print('e^x = ', np.exp(x))
print('2^x = ', np.exp2(x))
print('3^x = ', np.power(3,x))

x = [1, 3, 4]
e^x =  [ 2.71828183 20.08553692 54.59815003]
2^x =  [ 2.  8. 16.]
3^x =  [ 3 27 81]


In [33]:

print('ln(x) = ', np.log(x))
print('log2(x) = ', np.log2(x))
print('log10(x) = ', np.log10(x))

ln(x) =  [0.         1.09861229 1.38629436]
log2(x) =  [0.        1.5849625 2.       ]
log10(x) =  [0.         0.47712125 0.60205999]


In [36]:
# matrix multiplication:
X = np.array([1,3,2,4,5,6]).reshape(2,3)
print(X)
print('=======================')
print(X.T) # transpose X^T
print('=======================')
y = np.array([0,1,3]) #random vector
print(y)
print('=======================')
print(X.dot(y)) #x*y
print('=======================')
print(X.dot(X.T)) # x*X^T
print('=======================')
print(X.T.dot(X)) # x^T * X

[[1 3 2]
 [4 5 6]]
[[1 4]
 [3 5]
 [2 6]]
[0 1 3]
[ 9 23]
[[14 31]
 [31 77]]
[[17 23 26]
 [23 34 36]
 [26 36 40]]


In [37]:
# summing values in array
l = np.random.random(100)
sum(l)

53.95202953064628

In [38]:
np.sum(l)

53.952029530646264

In [40]:
# min and max
min(l), max(l)

(0.019792912458915457, 0.9973745279326072)

In [41]:
np.min(l),np.max(l)

(0.019792912458915457, 0.9973745279326072)

In [42]:
print(l.min(), l.max(), l.sum())

0.019792912458915457 0.9973745279326072 53.952029530646264


In [44]:
# for 2D array, axis = 0 means find min, max for columns
X.min(axis = 0)

array([1, 3, 2])

In [45]:
X.max(axis = 1)

array([3, 6])

In [60]:
# aggregation operations in numpy
print(np.sum(X))
print(np.prod(X))
print(np.mean(X))
print(np.std(X))
print(np.var(X))
print(np.min(X))
print(np.max(X))
print(np.argmax(X)) # index of max number
print(np.median(X))
print(np.percentile(X,5)) # rank based statistics
print(np.any(X)) # wether any element is true
print(np.all(X)) # wether all elements are true
print(X.argmin(axis = 0))
print(X.argmax(axis = 1))
print(X.argmin()) # only one index returned

21
720
3.5
1.707825127659933
2.9166666666666665
1
6
5
3.5
1.25
True
True
[0 0 0]
[1 2]
0


In [61]:
a = np.array([1,3,5])
b = np.array([2,4,6])
print(a+b)

[ 3  7 11]


In [62]:
a+5

array([ 6,  8, 10])

In [63]:
np.arange(3)+5

array([5, 6, 7])

In [65]:
np.ones((3,3))+np.arange(3)

array([[1., 2., 3.],
       [1., 2., 3.],
       [1., 2., 3.]])

In [66]:
np.array([[0],[1],[2]])+ np.arange(3)

array([[0, 1, 2],
       [1, 2, 3],
       [2, 3, 4]])

In [69]:
rand = np.random.random((10,3)) # 10 rows by 3 columns
rand

array([[0.53696213, 0.06721014, 0.38242973],
       [0.8751947 , 0.68051387, 0.48384802],
       [0.03366898, 0.43115329, 0.87523713],
       [0.36959565, 0.28233579, 0.62108862],
       [0.78088391, 0.62696803, 0.20817185],
       [0.16384003, 0.11855683, 0.84432392],
       [0.72156932, 0.61174485, 0.46659106],
       [0.92447846, 0.31328507, 0.83645408],
       [0.98743678, 0.09673985, 0.52291899],
       [0.27856851, 0.47429371, 0.88916088]])

In [71]:
rand_mean = rand.mean(0)
rand_mean

array([0.56721985, 0.37028014, 0.61302243])

In [73]:
rand_centered = rand - rand_mean
rand_centered

array([[-0.03025772, -0.30307   , -0.2305927 ],
       [ 0.30797485,  0.31023373, -0.12917441],
       [-0.53355087,  0.06087315,  0.26221471],
       [-0.1976242 , -0.08794435,  0.00806619],
       [ 0.21366406,  0.25668788, -0.40485058],
       [-0.40337982, -0.25172331,  0.23130149],
       [ 0.15434948,  0.2414647 , -0.14643137],
       [ 0.35725861, -0.05699507,  0.22343165],
       [ 0.42021693, -0.2735403 , -0.09010344],
       [-0.28865133,  0.10401356,  0.27613845]])

In [75]:
xMean = np.mean(X, axis = 0) # columns
d = X-xMean
print('columns-wise Mean')
print(xMean)
print('Mean normalized')
print(d)

columns-wise Mean
[2.5 4.  4. ]
Mean normalized
[[-1.5 -1.  -2. ]
 [ 1.5  1.   2. ]]


In [76]:
# Comparing numpy arrays
np.equal(a,b) # ==

array([False, False, False])

In [77]:
np.not_equal(a,b) # !=

array([ True,  True,  True])

In [78]:
np.less(a,b) # <

array([ True,  True,  True])

In [79]:
np.greater(a,b) #>

array([False, False, False])

In [80]:
np.less_equal(a,b) # <=

array([ True,  True,  True])

In [81]:
np.greater_equal(a,b) #>=

array([False, False, False])

In [83]:
rng = np.random.RandomState(0)
x = rng.randint(10, size=(3,4))
x

array([[5, 0, 3, 3],
       [7, 9, 3, 5],
       [2, 4, 7, 6]])

In [84]:
x<5

array([[False,  True,  True,  True],
       [False, False,  True, False],
       [ True,  True, False, False]])

In [85]:
# count how many values less than 5?
np.count_nonzero(x<5)

6

In [86]:
np.sum(x<5)

6

In [88]:
# how many values less than 6 in each row
np.sum(x<5, axis = 1)

array([3, 1, 2])

In [89]:
# are there any values greater than 8?
np.any(x>8)

True

In [90]:
# are there any values less than zero?
np.any(x<0)

False

In [91]:
# are all values less than 10?
np.all(x<10)

True

In [92]:
# are all values == 5?
np.all(x==5)

False

In [93]:
# are all values in each row less than 8?
np.all(x<8, axis = 1)

array([ True, False,  True])

In [94]:
# Boolean Operators on Numby arrays
np.logical_and(True,False)

False

In [95]:
np.logical_and([True,False],[False,False])

array([False, False])

In [98]:
x = np.arange(5)
print(x)

[0 1 2 3 4]


In [99]:
np.logical_and(x>1,x<4)

array([False, False,  True,  True, False])

In [100]:
a = np.array([True,True])
b = np.array([True,False])
a&b

array([ True, False])

In [101]:
a|b

array([ True,  True])

In [102]:
np.logical_not([True,False,0,1])

array([False,  True,  True, False])

In [104]:
# masking on numpy arrays
x = np.random.random((3,5))
x

array([[0.02873874, 0.78641072, 0.60020822, 0.21159922, 0.64442643],
       [0.9273337 , 0.66370814, 0.60665714, 0.77983584, 0.05053641],
       [0.18477108, 0.21868174, 0.6274481 , 0.18795441, 0.83456585]])

In [105]:
x<5

array([[ True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True]])

In [106]:
x[x<5] # index the values in array (masking)

array([0.02873874, 0.78641072, 0.60020822, 0.21159922, 0.64442643,
       0.9273337 , 0.66370814, 0.60665714, 0.77983584, 0.05053641,
       0.18477108, 0.21868174, 0.6274481 , 0.18795441, 0.83456585])

In [108]:
x = np.array([1,3,5,6,4,3]).reshape(2,3)
print(x<3)

[[ True False False]
 [False False False]]


In [109]:
x[x<3]=0
print(x)

[[0 3 5]
 [6 4 3]]


In [110]:
np.where(x<3,0,x)

array([[0, 3, 5],
       [6, 4, 3]])

In [113]:
subset = (x>0)&(x<7)
x[subset]= np.exp(x[subset])
x

array([[  0,  20, 148],
       [403,  54,  20]])

In [114]:
# fancy indexing
rand = np.random.RandomState(42)
x = rand.randint(100,size = 10)
print(x)

[51 92 14 71 60 20 82 86 74 74]


In [115]:
# to access different elemtents:
[x[3],x[7],x[2]]

[71, 86, 14]

In [116]:
# or you can pass single list or array of indices to obtain same results
ind = [3,7,2]
x[ind]

array([71, 86, 14])

In [117]:
x = np.array([1,3,4,5,6,7,8,9,0]).reshape(3,3)
print(x)

[[1 3 4]
 [5 6 7]
 [8 9 0]]


In [118]:
x[2,[2,0,1]]

array([0, 8, 9])

In [119]:
# compine fancy indexing with slicing:
x[1:,[2,0,1]]

array([[7, 5, 6],
       [0, 8, 9]])