<a href="https://colab.research.google.com/github/alshubati99/Data-Science-Study/blob/main/Lab2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Create a NumPy array named as 'myArray' of size 10x10 and fill it with random integers between 0 and 9

In [1]:
import numpy as np
np.random.seed(0)
myArray = np.random.randint(0, 10, size=(10, 10))
print(myArray)

[[5 0 3 3 7 9 3 5 2 4]
 [7 6 8 8 1 6 7 7 8 1]
 [5 9 8 9 4 3 0 3 5 0]
 [2 3 8 1 3 3 3 7 0 1]
 [9 9 0 4 7 3 2 7 2 0]
 [0 4 5 5 6 8 4 1 4 9]
 [8 1 1 7 9 9 3 6 7 2]
 [0 3 5 9 4 4 6 4 4 3]
 [4 4 8 4 3 7 5 5 0 1]
 [5 9 3 0 5 0 1 2 4 2]]


Display the shape of the array

In [2]:
print(myArray.shape)

(10, 10)


Display the sub-matrix having row indices 0,1,2 and column indices 3,4,5

In [3]:
sub_matrix = myArray[0:3, 3:6]
print(sub_matrix)

[[3 7 9]
 [8 1 6]
 [9 4 3]]


Reshape the submatrix above to a row vector

In [4]:
rv = sub_matrix.reshape(1, -1)
print(rv)

[[3 7 9 8 1 6 9 4 3]]


Sort the elements in the array row-side and print the sorted matrix

In [5]:
sorted_matrix = np.sort(myArray)
print(sorted_matrix)

[[0 2 3 3 3 4 5 5 7 9]
 [1 1 6 6 7 7 7 8 8 8]
 [0 0 3 3 4 5 5 8 9 9]
 [0 1 1 2 3 3 3 3 7 8]
 [0 0 2 2 3 4 7 7 9 9]
 [0 1 4 4 4 5 5 6 8 9]
 [1 1 2 3 6 7 7 8 9 9]
 [0 3 3 4 4 4 4 5 6 9]
 [0 1 3 4 4 4 5 5 7 8]
 [0 0 1 2 2 3 4 5 5 9]]


Create 1D array of ones and stack it to the previous array vertically

In [6]:
myArray = np.vstack((myArray, np.ones(10)))
print(myArray)

[[5. 0. 3. 3. 7. 9. 3. 5. 2. 4.]
 [7. 6. 8. 8. 1. 6. 7. 7. 8. 1.]
 [5. 9. 8. 9. 4. 3. 0. 3. 5. 0.]
 [2. 3. 8. 1. 3. 3. 3. 7. 0. 1.]
 [9. 9. 0. 4. 7. 3. 2. 7. 2. 0.]
 [0. 4. 5. 5. 6. 8. 4. 1. 4. 9.]
 [8. 1. 1. 7. 9. 9. 3. 6. 7. 2.]
 [0. 3. 5. 9. 4. 4. 6. 4. 4. 3.]
 [4. 4. 8. 4. 3. 7. 5. 5. 0. 1.]
 [5. 9. 3. 0. 5. 0. 1. 2. 4. 2.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]]


Add 10 to all elements in the array

In [7]:
myArray += 10
print(myArray)

[[15. 10. 13. 13. 17. 19. 13. 15. 12. 14.]
 [17. 16. 18. 18. 11. 16. 17. 17. 18. 11.]
 [15. 19. 18. 19. 14. 13. 10. 13. 15. 10.]
 [12. 13. 18. 11. 13. 13. 13. 17. 10. 11.]
 [19. 19. 10. 14. 17. 13. 12. 17. 12. 10.]
 [10. 14. 15. 15. 16. 18. 14. 11. 14. 19.]
 [18. 11. 11. 17. 19. 19. 13. 16. 17. 12.]
 [10. 13. 15. 19. 14. 14. 16. 14. 14. 13.]
 [14. 14. 18. 14. 13. 17. 15. 15. 10. 11.]
 [15. 19. 13. 10. 15. 10. 11. 12. 14. 12.]
 [11. 11. 11. 11. 11. 11. 11. 11. 11. 11.]]


Add the vector [0,1,2,3,4,5,6,7,8,9] to each row

In [8]:
myArray += np.array([0,1,2,3,4,5,6,7,8,9])
print(myArray)

[[15. 11. 15. 16. 21. 24. 19. 22. 20. 23.]
 [17. 17. 20. 21. 15. 21. 23. 24. 26. 20.]
 [15. 20. 20. 22. 18. 18. 16. 20. 23. 19.]
 [12. 14. 20. 14. 17. 18. 19. 24. 18. 20.]
 [19. 20. 12. 17. 21. 18. 18. 24. 20. 19.]
 [10. 15. 17. 18. 20. 23. 20. 18. 22. 28.]
 [18. 12. 13. 20. 23. 24. 19. 23. 25. 21.]
 [10. 14. 17. 22. 18. 19. 22. 21. 22. 22.]
 [14. 15. 20. 17. 17. 22. 21. 22. 18. 20.]
 [15. 20. 15. 13. 19. 15. 17. 19. 22. 21.]
 [11. 12. 13. 14. 15. 16. 17. 18. 19. 20.]]


Add 0 to all elements in the first row and 1 to second row and ... 10 to last row

In [9]:
add = np.arange(myArray.shape[0])[:, np.newaxis]
myArray += add
print(myArray)

[[15. 11. 15. 16. 21. 24. 19. 22. 20. 23.]
 [18. 18. 21. 22. 16. 22. 24. 25. 27. 21.]
 [17. 22. 22. 24. 20. 20. 18. 22. 25. 21.]
 [15. 17. 23. 17. 20. 21. 22. 27. 21. 23.]
 [23. 24. 16. 21. 25. 22. 22. 28. 24. 23.]
 [15. 20. 22. 23. 25. 28. 25. 23. 27. 33.]
 [24. 18. 19. 26. 29. 30. 25. 29. 31. 27.]
 [17. 21. 24. 29. 25. 26. 29. 28. 29. 29.]
 [22. 23. 28. 25. 25. 30. 29. 30. 26. 28.]
 [24. 29. 24. 22. 28. 24. 26. 28. 31. 30.]
 [21. 22. 23. 24. 25. 26. 27. 28. 29. 30.]]


Replace all elements of the array above 20 with 0

In [10]:
myArray[myArray > 20] = 0
print(myArray)

[[15. 11. 15. 16.  0.  0. 19.  0. 20.  0.]
 [18. 18.  0.  0. 16.  0.  0.  0.  0.  0.]
 [17.  0.  0.  0. 20. 20. 18.  0.  0.  0.]
 [15. 17.  0. 17. 20.  0.  0.  0.  0.  0.]
 [ 0.  0. 16.  0.  0.  0.  0.  0.  0.  0.]
 [15. 20.  0.  0.  0.  0.  0.  0.  0.  0.]
 [ 0. 18. 19.  0.  0.  0.  0.  0.  0.  0.]
 [17.  0.  0.  0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.]]


Replace all elements of array larger than 15 with their remainders when divided by 15

In [11]:
myArray[myArray > 15] = myArray[myArray > 15]%15
print(myArray)

[[15. 11. 15.  1.  0.  0.  4.  0.  5.  0.]
 [ 3.  3.  0.  0.  1.  0.  0.  0.  0.  0.]
 [ 2.  0.  0.  0.  5.  5.  3.  0.  0.  0.]
 [15.  2.  0.  2.  5.  0.  0.  0.  0.  0.]
 [ 0.  0.  1.  0.  0.  0.  0.  0.  0.  0.]
 [15.  5.  0.  0.  0.  0.  0.  0.  0.  0.]
 [ 0.  3.  4.  0.  0.  0.  0.  0.  0.  0.]
 [ 2.  0.  0.  0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.]]


Delete last 4 columns of the array

In [12]:
myArray = myArray[:, :-4]
print(myArray)

[[15. 11. 15.  1.  0.  0.]
 [ 3.  3.  0.  0.  1.  0.]
 [ 2.  0.  0.  0.  5.  5.]
 [15.  2.  0.  2.  5.  0.]
 [ 0.  0.  1.  0.  0.  0.]
 [15.  5.  0.  0.  0.  0.]
 [ 0.  3.  4.  0.  0.  0.]
 [ 2.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.]]


Delete last 3 rows of the array

In [13]:
myArray = myArray[:-3, :]
print(myArray)

[[15. 11. 15.  1.  0.  0.]
 [ 3.  3.  0.  0.  1.  0.]
 [ 2.  0.  0.  0.  5.  5.]
 [15.  2.  0.  2.  5.  0.]
 [ 0.  0.  1.  0.  0.  0.]
 [15.  5.  0.  0.  0.  0.]
 [ 0.  3.  4.  0.  0.  0.]
 [ 2.  0.  0.  0.  0.  0.]]


Swap second and third columns

In [14]:
myArray[:, [2, 3]] = myArray[:, [3, 2]]
print(myArray)

[[15. 11.  1. 15.  0.  0.]
 [ 3.  3.  0.  0.  1.  0.]
 [ 2.  0.  0.  0.  5.  5.]
 [15.  2.  2.  0.  5.  0.]
 [ 0.  0.  0.  1.  0.  0.]
 [15.  5.  0.  0.  0.  0.]
 [ 0.  3.  0.  4.  0.  0.]
 [ 2.  0.  0.  0.  0.  0.]]


Compute the sum of each row by multiplying the array with a column vector of ones and print the results

In [15]:
sum_result = np.sum(myArray * np.ones(myArray.shape[0])[:, np.newaxis], axis=1)[:, np.newaxis]
print(sum_result)

[[42.]
 [ 7.]
 [12.]
 [24.]
 [ 1.]
 [20.]
 [ 7.]
 [ 2.]]


Split the array into two matrics A and B, A is made up of first 4 columns and B inludes last 2 columns

In [16]:
A, B = myArray[:, :4],  myArray[:, 4:]
print(A, "\n\n", B)

[[15. 11.  1. 15.]
 [ 3.  3.  0.  0.]
 [ 2.  0.  0.  0.]
 [15.  2.  2.  0.]
 [ 0.  0.  0.  1.]
 [15.  5.  0.  0.]
 [ 0.  3.  0.  4.]
 [ 2.  0.  0.  0.]] 

 [[0. 0.]
 [1. 0.]
 [5. 5.]
 [5. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]]


Merge A and B back to the array

In [17]:
myArray = np.hstack((A, B))
print(myArray)

[[15. 11.  1. 15.  0.  0.]
 [ 3.  3.  0.  0.  1.  0.]
 [ 2.  0.  0.  0.  5.  5.]
 [15.  2.  2.  0.  5.  0.]
 [ 0.  0.  0.  1.  0.  0.]
 [15.  5.  0.  0.  0.  0.]
 [ 0.  3.  0.  4.  0.  0.]
 [ 2.  0.  0.  0.  0.  0.]]


Normalize the array so that each column is of zero mean and unit variance. Print the mean and variances of all columns to check for correctness

In [18]:
myArray = (myArray - np.mean(myArray, axis=0)) / np.std(myArray, axis=0)
print(myArray)
print(np.mean(myArray, axis=0))
print(np.std(myArray, axis=0))


[[ 1.27779825  2.30940108  0.89802651  2.55155182 -0.64930947 -0.37796447]
 [-0.52615222  0.         -0.53881591 -0.51031036 -0.1770844  -0.37796447]
 [-0.67648143 -0.8660254  -0.53881591 -0.51031036  1.71181587  2.64575131]
 [ 1.27779825 -0.28867513  2.33486893 -0.51031036  1.71181587 -0.37796447]
 [-0.97713984 -0.8660254  -0.53881591 -0.30618622 -0.64930947 -0.37796447]
 [ 1.27779825  0.57735027 -0.53881591 -0.51031036 -0.64930947 -0.37796447]
 [-0.97713984  0.         -0.53881591  0.30618622 -0.64930947 -0.37796447]
 [-0.67648143 -0.8660254  -0.53881591 -0.51031036 -0.64930947 -0.37796447]]
[ 1.38777878e-17  1.38777878e-17  8.32667268e-17 -4.16333634e-17
  0.00000000e+00 -4.16333634e-17]
[1. 1. 1. 1. 1. 1.]
